import React from 'react';
import { Link } from 'react-router-dom';
import SEO from '../components/SEO';
import './TermsAndConditions.css';

const TermsAndConditions = () => {
    return (
        <div className="terms-container">
            <SEO
                title="Terms and Conditions - LazarFlow"
                description="Terms and Conditions for using LazarFlow services."
                keywords="terms, conditions, legal, lazarflow"
                url="https://lazarflow.com/terms"
            />

            <header className="terms-header">
                <div className="header-content">
                    <h1>Terms and Conditions</h1>
                    <Link to="/" className="back-link">Back to Home</Link>
                </div>
            </header>

            <main className="terms-content">
                <section>
                    <h2>1. Introduction</h2>
                    <p>Welcome to LazarFlow. By accessing or using our website and services, you agree to be bound by these Terms and Conditions. Please read them carefully.</p>
                </section>

                <section>
                    <h2>2. Services</h2>
                    <p>LazarFlow provides esports tournament management tools, including points table generation and live leaderboards. Many of our features utilize advanced Artificial Intelligence (AI) and Optical Character Recognition (OCR) technologies.</p>
                </section>

                <section className="highlight-section">
                    <h2>3. AI Model Disclaimer & Limitation of Liability</h2>
                    <p>Our services incorporate AI and machine learning models to process data (such as screenshot analysis for scores). While we strive for high accuracy, AI technology is probabilistic and may occasionally produce errors, inaccuracies, or unexpected results.</p>
                    <p><strong>By using LazarFlow, you explicitly acknowledge and agree that:</strong></p>
                    <ul>
                        <li>LazarFlow is <strong>not responsible or liable</strong> for any mistakes, errors, misinterpretations, or hallucinations produced by our AI models or OCR engines.</li>
                        <li>You are solely responsible for verifying the accuracy of all data, results, and outputs generated by the service before relying on them, publishing them, or distributing them.</li>
                        <li>LazarFlow shall not be liable for any direct, indirect, incidental, special, consequential, or exemplary damages, including but not limited to damages for loss of profits, goodwill, use, data, or other intangible losses resulting from the use or inability to use the service or any errors in the AI-generated content.</li>
                    </ul>
                </section>

                <section className="highlight-section">
                    <h2>4. No Refunds Policy</h2>
                    <p>All sales are final. LazarFlow maintains a <strong>strict No Refunds Policy</strong> for all subscription plans, one-time purchases, and service fees.</p>
                    <ul>
                        <li>We do not provide refunds for partial subscription periods, unused services, or dissatisfaction with the AI model's performance.</li>
                        <li>Please ensure you review all features and compatibility before making a purchase.</li>
                    </ul>
                </section>

                <section className="highlight-section">
                    <h2>5. No Cancellations</h2>
                    <p>Once a subscription or service is purchased, it cannot be cancelled for a refund. You may cancel the renewal of a subscription for future billing cycles, but the current billing period continues until its expiration date.</p>
                </section>

                <section>
                    <h2>6. User Responsibilities</h2>
                    <p>You agree to use the service in compliance with all applicable laws and regulations. You are responsible for maintaining the confidentiality of your account and password and for restricting access to your computer.</p>
                </section>

                <section>
                    <h2>7. Modifications to Terms</h2>
                    <p>LazarFlow reserves the right to modify these terms at any time. We will notify users of any significant changes. Your continued use of the service after such changes constitutes your acceptance of the new Terms and Conditions.</p>
                </section>

                <section>
                    <h2>8. Contact Us</h2>
                    <p>If you have any questions about these Terms, please contact us at support@lazarflow.app.</p>
                </section>
            </main>

            <footer className="terms-footer">
                <p>&copy; {new Date().getFullYear()} LazarFlow. All rights reserved.</p>
            </footer>
        </div>
    );
};

export default TermsAndConditions;
