import React from 'react';
import { View, Text, StyleSheet, ScrollView, SafeAreaView, TouchableOpacity, StatusBar, Platform } from 'react-native';
import { FileText, Mail, ArrowLeft, AlertCircle } from 'lucide-react-native';
import { Theme } from '../styles/theme';

const TermsAndConditionsScreen = ({ navigation }) => {
    return (
        <SafeAreaView style={styles.safeArea}>
            <ScrollView style={styles.container} contentContainerStyle={styles.scrollContent}>
                <TouchableOpacity onPress={() => navigation.goBack()} style={styles.backButton}>
                    <ArrowLeft size={24} color={Theme.colors.textPrimary} />
                </TouchableOpacity>

                <View style={styles.header}>
                    <View style={styles.headerIcon}>
                        <FileText size={40} color={Theme.colors.accent} />
                    </View>
                    <Text style={styles.title}>Terms & Conditions</Text>
                    <Text style={styles.lastUpdated}>Last Updated: October 26, 2023</Text>
                </View>

                <Text style={styles.intro}>
                    Welcome to LazarFlow. By accessing or using our website and services, you agree to be bound by these Terms and Conditions. Please read them carefully.
                </Text>

                <Section title="1. Introduction">
                    <Text style={styles.sectionContent}>Welcome to LazarFlow. By accessing or using our website and services, you agree to be bound by these Terms and Conditions. Please read them carefully.</Text>
                </Section>

                <Section title="2. Services">
                    <Text style={styles.sectionContent}>LazarFlow provides esports lobby management tools, including points table generation and live leaderboards. Many of our features utilize advanced Artificial Intelligence (AI) and Optical Character Recognition (OCR) technologies.</Text>
                </Section>

                <Section title="3. AI Model Disclaimer & Limitation of Liability" highlighted>
                    <Text style={styles.sectionContent}>Our services incorporate AI and machine learning models to process data (such as screenshot analysis for scores). While we strive for high accuracy, AI technology is probabilistic and may occasionally produce errors, inaccuracies, or unexpected results.</Text>
                    <Text style={[styles.sectionContent, styles.bold]}>By using LazarFlow, you explicitly acknowledge and agree that:</Text>
                    <BulletPoint content="LazarFlow is not responsible or liable for any mistakes, errors, misinterpretations, or hallucinations produced by our AI models or OCR engines." />
                    <BulletPoint content="You are solely responsible for verifying the accuracy of all data, results, and outputs generated by the service before relying on them, publishing them, or distributing them." />
                    <BulletPoint content="LazarFlow shall not be liable for any direct, indirect, incidental, special, consequential, or exemplary damages, including but not limited to damages for loss of profits, goodwill, use, data, or other intangible losses resulting from the use or inability to use the service or any errors in the AI-generated content." />
                </Section>

                <Section title="4. No Refunds Policy" highlighted>
                    <Text style={styles.sectionContent}>All sales are final. LazarFlow maintains a strict No Refunds Policy for all subscription plans, one-time purchases, and service fees.</Text>
                    <BulletPoint content="We do not provide refunds for partial subscription periods, unused services, or dissatisfaction with the AI model's performance." />
                    <BulletPoint content="Please ensure you review all features and compatibility before making a purchase." />
                </Section>

                <Section title="5. No Cancellations" highlighted>
                    <Text style={styles.sectionContent}>Once a subscription or service is purchased, it cannot be cancelled for a refund. You may cancel the renewal of a subscription for future billing cycles, but the current billing period continues until its expiration date.</Text>
                </Section>

                <Section title="6. User Responsibilities">
                    <Text style={styles.sectionContent}>You agree to use the service in compliance with all applicable laws and regulations. You are responsible for maintaining the confidentiality of your account and password and for restricting access to your computer.</Text>
                </Section>

                <Section title="7. Modifications to Terms">
                    <Text style={styles.sectionContent}>LazarFlow reserves the right to modify these terms at any time. We will notify users of any significant changes. Your continued use of the service after such changes constitutes your acceptance of the new Terms and Conditions.</Text>
                </Section>

                <Section title="8. Contact Us">
                    <Text style={styles.sectionContent}>If you have any questions about these Terms, please contact us at support@lazarflow.app.</Text>
                    <View style={styles.contactCard}>
                        <Mail size={24} color={Theme.colors.accent} />
                        <Text style={styles.contactText}>support@lazarflow.app</Text>
                    </View>
                </Section>

                <View style={styles.footerContent}>
                    <Text style={styles.footerText}>© {new Date().getFullYear()} LazarFlow. All rights reserved.</Text>
                </View>
            </ScrollView>
        </SafeAreaView>
    );
};

const Section = ({ title, children, highlighted }) => (
    <View style={[styles.section, highlighted && styles.highlightedSection]}>
        <View style={styles.sectionHeader}>
            {highlighted && <AlertCircle size={20} color={Theme.colors.danger} style={styles.highlightIcon} />}
            <Text style={[styles.sectionTitle, highlighted && styles.highlightTitle]}>{title}</Text>
        </View>
        {children}
    </View>
);

const BulletPoint = ({ content }) => (
    <View style={styles.bulletRow}>
        <Text style={styles.bullet}>{'\u2022'}</Text>
        <Text style={styles.bulletContent}>{content}</Text>
    </View>
);

const styles = StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: Theme.colors.primary,
    },
    container: {
        flex: 1,
    },
    scrollContent: {
        padding: 24,
        paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight + 20 : 24,
    },
    backButton: {
        position: 'absolute',
        top: 24,
        left: 24,
        zIndex: 10,
        padding: 5,
    },
    header: {
        marginBottom: 30,
        alignItems: 'center',
        marginTop: 40, // Adjust for back button
    },
    headerIcon: {
        marginBottom: 15,
        backgroundColor: 'rgba(26, 115, 232, 0.1)',
        padding: 16,
        borderRadius: 50,
    },
    title: {
        fontSize: 28,
        fontFamily: Theme.fonts.inter.bold,
        color: Theme.colors.textPrimary,
        marginBottom: 8,
    },
    lastUpdated: {
        fontSize: 14,
        fontFamily: Theme.fonts.inter.regular,
        color: Theme.colors.textSecondary,
    },
    intro: {
        fontSize: 15,
        fontFamily: Theme.fonts.inter.regular,
        color: Theme.colors.textSecondary,
        lineHeight: 22,
        marginBottom: 30,
    },
    section: {
        marginBottom: 32,
        padding: 16,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: 'transparent',
    },
    highlightedSection: {
        backgroundColor: 'rgba(234, 67, 53, 0.05)',
        borderColor: 'rgba(234, 67, 53, 0.1)',
    },
    sectionHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 12,
    },
    sectionTitle: {
        fontSize: 18,
        fontFamily: Theme.fonts.inter.bold,
        color: Theme.colors.accent,
    },
    highlightTitle: {
        color: Theme.colors.danger,
    },
    sectionContent: {
        fontSize: 15,
        fontFamily: Theme.fonts.inter.regular,
        color: Theme.colors.textPrimary,
        lineHeight: 24,
    },
    highlightIcon: {
        marginRight: 10,
    },
    bulletRow: {
        flexDirection: 'row',
        marginBottom: 8,
        paddingLeft: 10,
    },
    bullet: {
        color: Theme.colors.accent,
        fontSize: 20,
        marginRight: 10,
    },
    bulletContent: {
        color: Theme.colors.textPrimary,
        fontFamily: Theme.fonts.inter.regular,
        fontSize: 15,
        lineHeight: 24,
        flex: 1,
    },
    bold: {
        fontFamily: Theme.fonts.inter.bold,
        color: Theme.colors.textPrimary,
    },
    contactCard: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: Theme.colors.secondary,
        padding: 20,
        borderRadius: 16,
        marginTop: 10,
        borderWidth: 1,
        borderColor: Theme.colors.border,
    },
    contactText: {
        marginLeft: 15,
        fontSize: 16,
        color: Theme.colors.accent,
        fontFamily: Theme.fonts.inter.bold,
    },
    footerContent: {
        marginTop: 20,
        paddingBottom: 40,
        alignItems: 'center',
    },
    footerText: {
        color: Theme.colors.textSecondary,
        fontFamily: Theme.fonts.inter.regular,
        fontSize: 14,
    },
});

export default TermsAndConditionsScreen;
